In [24]:
import numpy as np

In [23]:
# ------------ test cell -------------------
a = 0 
b = 0
c= a ^ b
print(c)   

0


In [103]:
# ------------------- inputs -----------------------
message = input("please enter the message to encrypt: ")
res = str(''.join(format(ord(i), '08b') for i in message))
#print(res)

initial = str(input("initial vector is --> "))

m = int(input("m = "))
clik = pow(2,m)

p_x = str(input("p(x) = "))
XOR_index = []

for i in range(len(p_x)):
    if p_x[i] == '^':
        XOR_index.append(int(p_x[i+1]))
    
    if p_x[i] == '+' and p_x[i+1] != 'x' and p_x[i+1] != 'X':
        XOR_index.append(0)
    
    if p_x[i] == '+' and i+2 < len(p_x) and p_x[i+2] != '^':
        XOR_index.append(1)

XOR_index_updated = XOR_index[::-1]
#print(XOR_index_updated)

In [104]:
def table_of_encryption(clk , init):
    
    table = np.zeros((clk, len(init)))
    key = np.zeros(clk)

    for j in range(len(init)):
        table[0][j] = int(init[j])

    key[0] = int(init[len(init)-1])

    for i in range(1,clk):
        c = 0

        for k in range(1,len(XOR_index)):
            c = c ^ int(table[i-1][(len(init)-1)-XOR_index[k]])
            #print((len(initial)-1)-XOR_index[k])

        table[i][0] = int(c)

        for j in range(1,len(init)):  
            table[i][j] = table[i-1][j-1]

        key[i] = table[i][len(init)-1]
 
    return key , table 

In [105]:
def table_of_decryption(clk , init):
    
    table = np.zeros((clk, len(init)))
    key = np.zeros(clk)

    for j in range(len(init)):
        table[0][j] = int(init[j])

    key[0] = int(init[len(init)-1])

    for i in range(1,clk):
        c = 0

        for k in range(1,len(XOR_index)):
            c = c ^ int(table[i-1][(len(init)-1)-XOR_index[k]])
            #print((len(initial)-1)-XOR_index[k])

        table[i][0] = int(c)

        for j in range(1,len(init)):  
            table[i][j] = table[i-1][j-1]

        key[i] = table[i][len(init)-1]
 
    return key , table 

In [106]:
def XOR_function(a , b):

    data = np.zeros(len(a))

    j = 0 
    for i in range(len(a)):

        if i % len(b) != 0:
             data[i] = int(a[i]) ^ int(b[j])
        
        else:
            j = 0
        
        j += 1

    return data

In [107]:
def make_string(a):

    s = ''

    for i in range(len(a)):
        if a[i] == 1:
            s = s + '1'
        
        elif a[i] == 0:
            s = s + '0'

    return s

In [108]:
def type_of_LFSRs(t , clk , init):

    c = np.array([])

    for i in range(1 , clk): 
        count = 0
        new_t = make_string(t[i])
        for j in range(len(init)):

            if new_t[j] == init[j]:
                count += 1
        
        #print(new_t)
        #print (init)
        #print(count)
        if count == len(init):
            c = np.append(c, i)

    #print(c)

    if c[0] == clk - 1:
        print("the type of LFSRs is: primitive")

    else:
        for i in range(len(c)):
            if c[i+1] % c[i] == 0:
                print("the type of LFSRs is: irreducible")
        
            else:
                print("the type of LFSRs is: reducible")


In [109]:
# ----------------------- cell like main ---------------------------------

key1, table1 = table_of_encryption(clik , initial)
encryption = XOR_function(res , key1)

key2, table2 = table_of_decryption(clik , initial)
decryption = XOR_function(encryption, key2)
decryption_in_string = make_string(decryption)

text_string = ''.join(chr(int(decryption_in_string[i:i+8], 2)) for i in range(0, len(decryption_in_string), 8))

print("table: ")
print(table1)
print("message in binary: ",res)
print("key: ", make_string(key1))
print("encrypted data in binary: ", make_string(encryption))
print("decrypted data data in binary: ",make_string(decryption))
print("decrypted data: ",text_string)

type_of_LFSRs(table1 , clik , initial)

table: 
[[1. 1. 0. 0.]
 [0. 1. 1. 0.]
 [1. 0. 1. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 1. 0.]
 [1. 0. 1. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 1. 0.]]
message in binary:  01101110011000010110111001100001
key:  0011010001101000
encrypted data in binary:  01011010000010010101101000001001
decrypted data data in binary:  01101110011000010110111001100001
decrypted data:  nana
the type of LFSRs is: irreducible


IndexError: index 2 is out of bounds for axis 0 with size 2